// Date: 12/24/2014 5:11:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.projectreddog.machinemod.model;

import java.io.IOException;
import java.util.HashMap;

import org.lwjgl.opengl.GL11;

import com.projectreddog.machinemod.entity.EntityMachineModRideable;
import com.projectreddog.machinemod.reference.Reference;
import com.projectreddog.machinemod.utility.MachineModModelHelper;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.block.model.IBakedModel;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.obj.OBJLoader;
import net.minecraftforge.client.model.obj.OBJModel;

public class ModelDrillingRig extends ModelTransportable {
	// fields

	public OBJModel objModel;
	private HashMap<String, IBakedModel> modelParts;

	public ModelDrillingRig() {

		try {
			objModel = (OBJModel) OBJLoader.INSTANCE.loadModel(new ResourceLocation(Reference.MOD_ID.toLowerCase(), "models/drillingrig.obj"));
			modelParts = MachineModModelHelper.getModelsForGroups(objModel);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		// myModel.renderAll();

		// this.renderGroupObject("Body_Cube");
		GL11.glTranslatef(0f, -0.f, -2.0f);

		this.renderGroupObject("Object.1");
		this.renderGroupObject("Object.2");
		this.renderGroupObject("Object.3");
		this.renderGroupObject("Object.4");
		this.renderGroupObject("Object.5");
		this.renderGroupObject("Object.6");
		this.renderGroupObject("Object.7");
		this.renderGroupObject("Object.8");
		this.renderGroupObject("Object.9");
		this.renderGroupObject("Object.10");
		this.renderGroupObject("Object.11");
		this.renderGroupObject("Object.12");
		this.renderGroupObject("Object.13");
		this.renderGroupObject("Object.14");
		this.renderGroupObject("Object.15");
		this.renderGroupObject("Object.16");
		this.renderGroupObject("Object.17");
		this.renderGroupObject("Object.18");

		this.renderGroupObject("Object.21");
		this.renderGroupObject("Object.22");
		GL11.glTranslatef(0f, -5.f, -3.25f);
		float currentAngle2 = 0;
		int depth = 0;
		if (entity != null) {
			float currentAngle = (((EntityMachineModRideable) entity).Attribute1);
			if (currentAngle > 90) {
				currentAngle = 90;
			}
			currentAngle = currentAngle - 90;
			GL11.glRotatef(currentAngle, 1, 0, 0);
			currentAngle2 = (((((EntityMachineModRideable) entity).Attribute1) - 90) / 5);
			if (depth < 0) {
				depth = 0;
			}

		} else {
			GL11.glRotatef(-90, 1, 0, 0);

		}
		// this.renderGroupObject("Arm_Cube.001");

		this.renderGroupObject("Object.20");
		GL11.glTranslatef(-.55f, -0.30f, -2.1f);

		if (currentAngle2 > 0) {
			GL11.glTranslatef(0f, currentAngle2, 0);
			GL11.glRotatef(currentAngle2 * 180, 0, 1, 0);

		}

		this.renderGroupObject("Object.19");
	}

	public void renderGroupObject(String groupName) {
		MachineModModelHelper.renderBakedModel(modelParts.get(groupName));

	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
	}

	public ResourceLocation getTexture() {

		return new ResourceLocation("machinemod", Reference.MODEL_DRILLINGRIG_TEXTURE_LOCATION);
	}

}
