// Date: 12/24/2014 5:11:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.projectreddog.machinemod.model;

import java.io.IOException;
import java.util.HashMap;

import com.projectreddog.machinemod.reference.Reference;
import com.projectreddog.machinemod.utility.MachineModModelHelper;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.block.model.IBakedModel;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.obj.OBJLoader;
import net.minecraftforge.client.model.obj.OBJModel;

public class ModelTractor extends ModelTransportable {
	// fields

	public OBJModel objModel;
	private HashMap<String, IBakedModel> modelParts;

	public ModelTractor() {

		try {
			objModel = (OBJModel) OBJLoader.INSTANCE.loadModel(new ResourceLocation(Reference.MOD_ID.toLowerCase(), "models/modeltractor.obj"));
			modelParts = MachineModModelHelper.getModelsForGroups(objModel);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void renderGroupObject(String groupName) {
		MachineModModelHelper.renderBakedModel(modelParts.get(groupName));

	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		// myModel.renderAll();
		// will now call rendering for each individual object
		this.renderGroupObject("Object.3");
		this.renderGroupObject("Object.4");
		this.renderGroupObject("Object.5");
		this.renderGroupObject("Object.6");
		this.renderGroupObject("Object.7");
		this.renderGroupObject("Object.8");
		this.renderGroupObject("Object.9");
		this.renderGroupObject("Object.10");
		this.renderGroupObject("Object.11");
		this.renderGroupObject("Object.12");
		this.renderGroupObject("Object.13");
		this.renderGroupObject("Object.14");
		this.renderGroupObject("Object.15");
		this.renderGroupObject("Object.16");
		this.renderGroupObject("Object.17");
		this.renderGroupObject("Object.18");
		this.renderGroupObject("Object.19");
		this.renderGroupObject("Object.20");
		this.renderGroupObject("Object.21");
		this.renderGroupObject("Object.22");
		this.renderGroupObject("Object.23");
		this.renderGroupObject("Object.24");
		this.renderGroupObject("Object.25");
		this.renderGroupObject("Object.26");
		this.renderGroupObject("Object.27");
		this.renderGroupObject("Object.28");
		this.renderGroupObject("Object.29");
		this.renderGroupObject("Object.30");
		this.renderGroupObject("Object.31");
		this.renderGroupObject("Object.32");
		this.renderGroupObject("Object.33");
		this.renderGroupObject("Object.34");
		this.renderGroupObject("Object.35");
		this.renderGroupObject("Object.36");
		this.renderGroupObject("Object.37");
		this.renderGroupObject("Object.38");
		this.renderGroupObject("Object.39");
		this.renderGroupObject("Object.40");
		this.renderGroupObject("Object.41");
		this.renderGroupObject("Object.42");

	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
	}

	public ResourceLocation getTexture() {

		return new ResourceLocation("machinemod", Reference.MODEL_TRACTOR_TEXTURE_LOCATION);
	}

}
